<?php

namespace AppBundle\Repository;

use AppBundle\Model\Filter;
use Doctrine\ORM\EntityRepository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    public function getFilteredExpenses(Filter $filter, $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('e');
        $qb->from('AppBundle:Expense', 'e');

        $qb->andWhere('e.userId = :userId');
        $qb->setParameter('userId', $user->getId());

        if (!empty($filter->getCategoryId())) {
            $qb
                ->andWhere('e.categoryId = :categoryId')
                ->setParameter('categoryId', $filter->getCategoryId());
        }

        if (!empty($filter->getName())) {
            $qb
                ->andWhere('e.title like :name')
                ->setParameter('name', '%' . $filter->getName() . '%');
        }

        if (!empty($filter->getPriority())) {
            $qb
                ->andWhere('e.priority = :priority')
                ->setParameter('priority', $filter->getPriority());
        }

        if (!empty($filter->getDateFrom())) {
            $qb
                ->andWhere('e.date >= :from')
                ->setParameter('from', $filter->getDateFrom());
        }

        if (!empty($filter->getDateTo())) {
            $qb
                ->andWhere('e.date <= :to')
                ->setParameter('to', $filter->getDateTo());
        }

        if (!empty($filter->getSortBy())) {
            $qb->orderBy('e.' . $filter->getSortBy(), 'ASC');
        }

        return $qb->getQuery()->getResult();
    }
}
